In [264]:
import numpy as np

In [265]:
import pandas as pd

In [266]:
credit=pd.read_csv("tmdb_5000_credits.csv")
movie=pd.read_csv("tmdb_5000_movies.csv")

In [267]:
movie.sample(10)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
2728,13400000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",http://www.lastgodfathermovie.com/,70829,[],en,The Last Godfather,"Young-goo the son of mafia boss Don Carini, is...",0.680753,[],[],2010-12-29,16700000,100.0,"[{""iso_639_1"": ""ko"", ""name"": ""\ud55c\uad6d\uc5...",Released,NaN,The Last Godfather,4.7,7
3117,3200000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,39037,"[{""id"": 10183, ""name"": ""independent film""}]",en,The Good Guy,Ambitious young Manhattanite and urban conserv...,2.631688,"[{""name"": ""Belladonna Productions"", ""id"": 2341...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-04-25,0,90.0,"[{""iso_639_1"": ""ru"", ""name"": ""P\u0443\u0441\u0...",Released,NaN,The Good Guy,5.4,59
2581,15000000,"[{""id"": 9648, ""name"": ""Mystery""}, {""id"": 27, ""...",NaN,9424,"[{""id"": 236, ""name"": ""suicide""}, {""id"": 572, ""...",en,Disturbing Behavior,Steve Clark (James Marsden) is a newcomer in t...,9.378688,"[{""name"": ""Village Roadshow Pictures"", ""id"": 7...","[{""iso_3166_1"": ""AU"", ""name"": ""Australia""}, {""...",1998-07-24,17507368,84.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,In Cradle Bay it doesn’t matter if you’re not ...,Disturbing Behavior,5.5,104
1777,26000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://paulblartmallcop.com/,14560,"[{""id"": 41180, ""name"": ""security guard""}, {""id...",en,Paul Blart: Mall Cop,Mild-mannered Paul Blart (Kevin James) has alw...,31.250383,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-01-15,183293131,91.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Safety Never Takes A Holiday.,Paul Blart: Mall Cop,5.2,788
3837,3500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,11363,"[{""id"": 380, ""name"": ""brother brother relation...",en,She's the One,"Mickey, a free-spirited New York cabbie, and F...",8.406025,"[{""name"": ""Fox Searchlight Pictures"", ""id"": 43}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1996-08-26,9482579,96.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,A romantic comedy about two brothers... and th...,She's the One,5.7,70
3951,0,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,79940,"[{""id"": 1946, ""name"": ""restaurant""}, {""id"": 19...",en,Tim and Eric's Billion Dollar Movie,Two guys get a billion dollars to make a movie...,1.753110,"[{""name"": ""2929 Productions"", ""id"": 846}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-02,0,94.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Tim and Eric's Billion Dollar Movie,5.2,34
2897,7500000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 878, ""...",http://www.miramax.com/cypher/,10133,"[{""id"": 848, ""name"": ""double life""}, {""id"": 15...",en,Cypher,"An unsuspecting, disenchanted man finds himsel...",11.636883,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2002-10-01,0,95.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never forget who you are,Cypher,6.7,192
2950,11000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,63020,"[{""id"": 1900, ""name"": ""immigration""}, {""id"": 1...",en,The Perez Family,In the midst of the Mariel boat lift -- a hurr...,1.187671,"[{""name"": ""Samuel Goldwyn Company, The"", ""id"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1995-05-12,2832826,113.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"On the way to finding a family, she found love.",The Perez Family,6.6,9
3802,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...",NaN,14902,"[{""id"": 279, ""name"": ""usa""}, {""id"": 1705, ""nam...",en,1776,The film focuses on the representatives of the...,1.807571,"[{""name"": ""Columbia Pictures Corporation"", ""id...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1972-11-09,0,142.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The award winning musical comes to the screen!,1776,7.1,20
3413,6900000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 53, ""nam...",NaN,82505,"[{""id"": 10707, ""name"": ""mother daughter relati...",en,House at the End of the Street,A mother and daughter move to a new town and f...,25.613197,"[{""name"": ""A Bigger Boat"", ""id"": 5855}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-09-21,44287131,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Fear reaches out... for the girl next door.,House at the End of the Street,5.6,555

In [268]:
credit.sample(10)

,movie_id,title,cast,crew
3505,38940,Men of War,"[{""cast_id"": 4, ""character"": ""Nick Gunar"", ""cr...","[{""credit_id"": ""52fe46ec9251416c910643db"", ""de..."
2364,18701,Being Julia,"[{""cast_id"": 1, ""character"": ""Jimmie Langton"",...","[{""credit_id"": ""52fe47929251416c7509e4a3"", ""de..."
4390,25983,The House of the Devil,"[{""cast_id"": 1, ""character"": ""Samantha"", ""cred...","[{""credit_id"": ""59b57662c3a36809d3000de7"", ""de..."
932,752,V for Vendetta,"[{""cast_id"": 23, ""character"": ""Evey Hammond"", ...","[{""credit_id"": ""52fe4270c3a36847f801ebf5"", ""de..."
2600,9686,New York Stories,"[{""cast_id"": 1, ""character"": ""Sheldon"", ""credi...","[{""credit_id"": ""52fe451bc3a36847f80bce5d"", ""de..."
2897,10133,Cypher,"[{""cast_id"": 1, ""character"": ""Morgan Sullivan""...","[{""credit_id"": ""52fe43309251416c75006f07"", ""de..."
775,10384,Supernova,"[{""cast_id"": 6, ""character"": ""Nick Vanzant"", ""...","[{""credit_id"": ""52fe43639251416c7500e78f"", ""de..."
486,274854,The Last Witch Hunter,"[{""cast_id"": 0, ""character"": ""Kaulder"", ""credi...","[{""credit_id"": ""56a4febdc3a368388b0079f2"", ""de..."
2246,4960,"Synecdoche, New York","[{""cast_id"": 3, ""character"": ""Caden Cotard"", ""...","[{""credit_id"": ""52fe43e8c3a36847f80777e3"", ""de..."
3883,8469,Animal House,"[{""cast_id"": 1, ""character"": ""John \""Bluto\"" B...","[{""credit_id"": ""52fe44acc3a36847f80a3975"", ""de..."

In [269]:
movie=movie.merge(credit,on='title')

In [270]:
movie.sample(10)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
578,75000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10751, ""...",http://www.munkyourself.com/,23398,"[{""id"": 10986, ""name"": ""chipmunk""}, {""id"": 109...",en,Alvin and the Chipmunks: The Squeakquel,"Pop sensations Alvin, Simon and Theodore end u...",29.412262,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",...,88.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The Boys are back in town... and they have com...,Alvin and the Chipmunks: The Squeakquel,5.4,666,23398,"[{""cast_id"": 1, ""character"": ""Toby"", ""credit_i...","[{""credit_id"": ""52fe4468c3a368484e021627"", ""de..."
1336,38000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",http://howtobesinglemovie.com/,259694,"[{""id"": 242, ""name"": ""new york""}, {""id"": 818, ...",en,How to Be Single,New York City is full of lonely hearts seeking...,46.078371,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...",...,110.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Welcome to the party,How to Be Single,5.9,1201,259694,"[{""cast_id"": 8, ""character"": ""Alice Kepley"", ""...","[{""credit_id"": ""56be233492514140a600221d"", ""de..."
3256,8000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...",NaN,14429,"[{""id"": 6270, ""name"": ""high school""}, {""id"": 1...",en,Drive Me Crazy,Nicole and Chase live next door to each other ...,4.482714,"[{""name"": ""Twentieth Century Fox Film Corporat...",...,91.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The last guy she wants is the only one she needs.,Drive Me Crazy,5.8,62,14429,"[{""cast_id"": 1, ""character"": ""Nicole Maris"", ""...","[{""credit_id"": ""52fe45f29251416c75067ea3"", ""de..."
648,65000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",NaN,11820,"[{""id"": 171452, ""name"": ""faculty""}, {""id"": 171...",en,Mona Lisa Smile,"The story of Katherine Ann Watson, a feminist ...",19.718544,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,117.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"In a world that told them how to think, she sh...",Mona Lisa Smile,6.5,393,11820,"[{""cast_id"": 11, ""character"": ""Katherine Ann W...","[{""credit_id"": ""52fe448b9251416c7503894b"", ""de..."
2311,0,"[{""id"": 28, ""name"": ""Action""}]",NaN,244339,[],cn,逃出生天,"On the hottest day in 50 years, a serious fire...",1.583918,"[{""name"": ""Sun Entertainment Culture"", ""id"": 2...",...,107.0,"[{""iso_639_1"": ""cn"", ""name"": ""\u5e7f\u5dde\u8b...",Released,NaN,Out of Inferno,5.8,11,244339,"[{""cast_id"": 4, ""character"": """", ""credit_id"": ...","[{""credit_id"": ""52fe4ef0c3a36847f82b1f89"", ""de..."
1647,30000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,9042,"[{""id"": 6201, ""name"": ""fall""}, {""id"": 9786, ""n...",en,The Cave,After a group of biologists discovers a huge n...,10.756266,"[{""name"": ""Lakeshore Entertainment"", ""id"": 126...",...,97.0,"[{""iso_639_1"": ""cs"", ""name"": ""\u010cesk\u00fd""...",Released,There are places man was never meant to go.,The Cave,5.1,202,9042,"[{""cast_id"": 1, ""character"": ""Jack McAllister""...","[{""credit_id"": ""52fe44d5c3a36847f80acc27"", ""de..."
1805,26000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",NaN,31640,"[{""id"": 642, ""name"": ""robbery""}, {""id"": 1419, ...",en,Blood and Wine,A man who has failed as a father and husband c...,1.492056,"[{""name"": ""Fox Searchlight Pictures"", ""id"": 43...",...,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,There is no honour amongst thieves.,Blood and Wine,5.5,34,31640,"[{""cast_id"": 1, ""character"": ""Alex Gates"", ""cr...","[{""credit_id"": ""532813d19251411a22001e36"", ""de..."
58,140000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",NaN,5174,"[{""id"": 1704, ""name"": ""ambassador""}]",en,Rush Hour 3,After an attempted assassination on Ambassador...,22.571780,"[{""name"": ""New Line Cinema"", ""id"": 12}]",...,91.0,"[{""iso_639_1"": ""la"", ""name"": ""Latin""}, {""iso_6...",Released,The Rush Is On!,Rush Hour 3,6.1,783,5174,"[{""cast_id"": 2, ""character"": ""Det. James Carte...","[{""credit_id"": ""52fe43fac3a36847f807b5bd"", ""de..."
277,150000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://www.mgm.com/#/our-titles/233/Casino-Roy...,36557,"[{""id"": 131, ""name"": ""italy""}, {""id"": 383, ""na...",en,Casino Royale,"Le Chiffre, a banker to the world's terrorists...",88.935165,"[{""name"": ""Eon Productions"", ""id"": 7576}, {""na...",...,144.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Everyone has a past. Every legend has a beginn...,Casino Royale,7.3,3855,36557,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""53ac1fd7c3a3684bc8001908"", ""de..."
834,55000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,2320,"[{""id"": 258, ""name"": ""bomb""}, {""id"": 1336, ""na...",en,Executive Decision,Terrorists hijack a 747 inbound to Washington ...,17.231675,"[{""name"": ""Silver Pictures"", ""id"": 1885}, {""na...",...,133.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Fasten your seat belts,Executive Decision,5.8,256,2320,"[{""cast_id"": 2, ""character"": ""Dr. David Grant""...","[{""credit_id"": ""52fe434ec3a36847f804a22d"", ""de..."

In [271]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [272]:
#genres
#id
#keywords
#overview
#original_language
#production_companies
#production_countries
#spoken_languages
#title
#cast
#crew
movie=movie[['movie_id','title','overview','genres','keywords','production_companies','production_countries','spoken_languages','cast','crew']]

In [273]:
movie.sample(10)

,movie_id,title,overview,genres,keywords,production_companies,production_countries,spoken_languages,cast,crew
1019,2148,The Cotton Club,The story of the people that frequented Harlem...,"[{""id"": 10402, ""name"": ""Music""}, {""id"": 18, ""n...","[{""id"": 1416, ""name"": ""jazz""}, {""id"": 3017, ""n...","[{""name"": ""Orion Pictures"", ""id"": 41}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[{""cast_id"": 17, ""character"": ""Dixie Dwyer"", ""...","[{""credit_id"": ""52fe433ac3a36847f80443ad"", ""de..."
329,122,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 603, ""name"": ""elves""}, {""id"": 606, ""na...","[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 12, ""character"": ""Frodo Baggins"",...","[{""credit_id"": ""52fe421bc3a36847f80046c3"", ""de..."
2892,9260,Welcome to Collinwood,Five hapless inner-city low-lifes attempt to b...,"[{""id"": 35, ""name"": ""Comedy""}]","[{""id"": 8430, ""name"": ""safe""}, {""id"": 9714, ""n...","[{""name"": ""Section Eight"", ""id"": 129}, {""name""...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 17, ""character"": ""Riley"", ""credit...","[{""credit_id"": ""52fe44dec3a36847f80aec21"", ""de..."
2798,43867,The Prisoner of Zenda,An Englishman on a Ruritarian holiday must imp...,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...","[{""id"": 1930, ""name"": ""kidnapping""}, {""id"": 25...","[{""name"": ""United Artists"", ""id"": 60}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, ...","[{""cast_id"": 3, ""character"": ""Major Rudolf Ras...","[{""credit_id"": ""52fe4667c3a36847f80fd01b"", ""de..."
710,5994,The Family Man,"Jack's lavish, fast-paced lifestyle changes on...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 1022, ""name"": ""workaholic""}, {""id"": 34...","[{""name"": ""Universal Pictures"", ""id"": 33}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 11, ""character"": ""Jack Campbell"",...","[{""credit_id"": ""52fe4434c3a36847f80885ad"", ""de..."
210,415,Batman & Robin,Along with crime-fighting partner Robin and ne...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 848, ""name"": ""double life""}, {""id"": 84...","[{""name"": ""PolyGram Filmed Entertainment"", ""id...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 4, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""59b66a169251417cbc011ec4"", ""de..."
1326,14325,The Express,"Based on the incredible true story, The Expres...","[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 579, ""name"": ""american football""}, {""i...","[{""name"": ""Davis Entertainment"", ""id"": 1302}, ...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 1, ""character"": ""Ernie Davis"", ""c...","[{""credit_id"": ""55be345b9251413e51004b35"", ""de..."
3533,138697,Don Jon,"A New Jersey guy dedicated to his family, frie...","[{""id"": 10749, ""name"": ""Romance""}, {""id"": 35, ...","[{""id"": 445, ""name"": ""pornography""}, {""id"": 57...","[{""name"": ""Voltage Pictures"", ""id"": 10255}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 8, ""character"": ""Jon Martello, Jr...","[{""credit_id"": ""52fe4c53c3a368484e1b2707"", ""de..."
1885,11543,Kingpin,After bowler Roy Munson swindles the wrong cro...,"[{""id"": 35, ""name"": ""Comedy""}]","[{""id"": 6075, ""name"": ""sport""}, {""id"": 167550,...","[{""name"": ""Motion Picture Corporation of Ameri...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 13, ""character"": ""Roy Munson"", ""c...","[{""credit_id"": ""52fe44569251416c75031251"", ""de..."
3117,268171,Elsa & Fred,"Aged, embittered widower, Fred learns to enjoy...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10751, ""...","[{""id"": 33476, ""name"": ""widower""}]","[{""name"": ""Riverside Entertainment"", ""id"": 562...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""}]","[{""cast_id"": 0, ""character"": ""Elsa Hayes"", ""cr...","[{""credit_id"": ""53666d7f0e0a2647d4003708"", ""de..."

In [274]:
#ID
#Title
#Tag
movie.isnull().sum()

movie_id                0
title                   0
overview                3
genres                  0
keywords                0
production_companies    0
production_countries    0
spoken_languages        0
cast                    0
crew                    0
dtype: int64

In [275]:
movie.dropna(inplace=True)

In [276]:
movie.duplicated().sum()

np.int64(0)

In [277]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i["name"])
    return L

In [278]:
movie['genres']=movie['genres'].apply(convert)

In [279]:
movie.sample(15)

,movie_id,title,overview,genres,keywords,production_companies,production_countries,spoken_languages,cast,crew
3464,36739,School Daze,In the South of the United States are taking p...,"[Comedy, Drama]","[{""id"": 4344, ""name"": ""musical""}]","[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 18, ""character"": ""Leeds"", ""credit...","[{""credit_id"": ""52fe46069251416c910468f9"", ""de..."
1575,8292,Four Brothers,Four adopted brothers return to their Detroit ...,"[Action, Crime]","[{""id"": 380, ""name"": ""brother brother relation...","[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, ...","[{""cast_id"": 2, ""character"": ""Bobby Mercer"", ""...","[{""credit_id"": ""57d062ebc3a3681629001a5d"", ""de..."
1492,1892,Return of the Jedi,As Rebel leaders map their strategy for an all...,"[Adventure, Action, Science Fiction]","[{""id"": 526, ""name"": ""rebel""}, {""id"": 1155, ""n...","[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twe...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 8, ""character"": ""Luke Skywalker"",...","[{""credit_id"": ""52fe431ec3a36847f803bc0f"", ""de..."
1268,7288,Duplex,"When a young couple buys their dream home, the...","[Action, Comedy, Thriller]",[],"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 1, ""character"": ""Alex Rose"", ""cre...","[{""credit_id"": ""52fe4477c3a36847f809798b"", ""de..."
3331,2011,Persepolis,"In 1970s Iran, Marjane 'Marji' Statrapi watche...","[Animation, Drama]","[{""id"": 393, ""name"": ""civil war""}, {""id"": 970,...","[{""name"": ""Sony Pictures Classics"", ""id"": 58},...","[{""iso_3166_1"": ""FR"", ""name"": ""France""}, {""iso...","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[{""cast_id"": 7, ""character"": ""Marjane adulte e...","[{""credit_id"": ""52fe432cc3a36847f803fc85"", ""de..."
844,10632,The Hunted,"In the wilderness of British Columbia, two hun...","[Drama, Action, Thriller, Crime]","[{""id"": 414, ""name"": ""hunter""}, {""id"": 1812, ""...","[{""name"": ""Lakeshore Entertainment"", ""id"": 126...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 1, ""character"": ""L.T. Bonham"", ""c...","[{""credit_id"": ""5587d0059251411efc0006d3"", ""de..."
1002,15268,Street Fighter: The Legend of Chun-Li,"When a teenager, Chun-Li witnesses the kidnapp...","[Action, Adventure, Science Fiction, Thriller]","[{""id"": 779, ""name"": ""martial arts""}, {""id"": 9...","[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 1, ""character"": ""Chun-Li"", ""credi...","[{""credit_id"": ""52fe46499251416c75073839"", ""de..."
3877,12586,Bella,An international soccer star is on his way to ...,"[Drama, Romance]","[{""id"": 828, ""name"": ""waitress""}, {""id"": 966, ...","[{""name"": ""Mpower Pictures"", ""id"": 5294}, {""na...","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[{""cast_id"": 28, ""character"": ""Nina"", ""credit_...","[{""credit_id"": ""52fe45009251416c750485f1"", ""de..."
2386,43434,Carlos,"The story of Venezuelan revolutionary, Ilich R...","[Crime, Drama, Thriller, History]","[{""id"": 1419, ""name"": ""gun""}, {""id"": 7336, ""na...","[{""name"": ""Egoli Tossell Film AG"", ""id"": 2254}...","[{""iso_3166_1"": ""FR"", ""name"": ""France""}, {""iso...","[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...","[{""cast_id"": 4, ""character"": ""Ilich Ram\u00edr...","[{""credit_id"": ""57352b61c3a3680253000870"", ""de..."
2805,23631,Machete,After being set-up and betrayed by the man who...,"[Action, Comedy, Thriller]","[{""id"": 2173, ""name"": ""illegal immigration""}, ...","[{""name"": ""Dune Entertainment"", ""id"": 444}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[{""cast_id"": 4, ""character"": ""Machete"", ""credi...","[{""credit_id"": ""52fe4472c3a368484e0236cd"", ""de..."
2754,264660,Ex Machina,"Caleb, a 26 year old coder at the world's larg...","[Drama, Science Fiction]","[{""id"": 246, ""name"": ""dancing""}, {""id"": 310, ""...","[{""name"": ""DNA Films"", ""id"": 284}, {""name"": ""U...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 1, ""character"": ""Caleb Smith"", ""c...","[{""credit_id"": ""5535b633c3a368523e004fe5"", ""de..."
1656,11058,Godsend,A couple agree to have their deceased son clon...,"[Drama, Horror, Science Fiction, Thriller]","[{""id"": 222, ""name"": ""schizophrenia""}, {""id"": ...","[{""name"": ""Lions Gate Films"", ""id"": 35}, {""nam...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 1, ""character"": ""Paul Duncan"", ""c...","[{""credit_id"": ""52fe43ed9251416c7502357f"", ""de..."
421,1949,Zodiac,The true story of the investigation of 'The Zo...,"[Crime, Drama, Mystery, Thriller]","[{""id"": 387, ""name"": ""california""}, {""id"": 582...","[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 13, ""character"": ""Robert Graysmit...","[{""credit_id"": ""5669e7e99251415ec500222d"", ""de..."
3851,38007,Ira & Abby,"A neurotic, young psychology student, with low...","[Comedy, Romance]","[{""id"": 10183, ""name"": ""independent film""}]",[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",[],"[{""cast_id"": 2, ""character"": ""Ira Black"", ""cre...","[{""credit_id"": ""52fe46889251416c910577bd"", ""de..."
1479,18254,Reds,A radical American journalist becomes involved...,"[Drama, History]","[{""id"": 736, ""name"": ""journalist""}, {""id"": 346...","[{""name"": ""Barclays Mercantile Industrial Fina...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""de"", ""name"": ""Deutsch""}, {""iso...","[{""cast_id"": 2, ""character"": ""John Reed"", ""cre...","[{""credit_id"": ""5745432b92514153c10011f2"", ""de..."

In [280]:
movie['keywords']=movie['keywords'].apply(convert)

In [281]:
movies=movie

In [282]:
movies.sample(10)

,movie_id,title,overview,genres,keywords,production_companies,production_countries,spoken_languages,cast,crew
4713,50497,When the Lights Went Out,"Yorkshire, 1974, the Maynard family moves into...","[Thriller, Drama, Horror]","[newspaper, exorcism, poltergeist, priest, hau...","[{""name"": ""Kintop Pictures"", ""id"": 1490}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 1, ""character"": ""Jenny"", ""credit_...","[{""credit_id"": ""538746190e0a26144d003d19"", ""de..."
4466,25212,Deterrence,The President of the United States must deal w...,"[Action, Drama, Mystery, Thriller]","[diner, judgment call]","[{""name"": ""Battleplan Productions"", ""id"": 2108...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 1, ""character"": ""Walter Emerson"",...","[{""credit_id"": ""587265c992514135610182c1"", ""de..."
138,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","[Action, Adventure, Family, Fantasy]","[fire, ice, war ship, prince, kingdom, water, ...","[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 2, ""character"": ""Aang"", ""credit_i...","[{""credit_id"": ""52fe433f9251416c750092c9"", ""de..."
3733,1088,Whale Rider,"On the east coast of New Zealand, the Whangara...","[Drama, Family]","[ocean, loss of mother, tradition, loss of bro...","[{""name"": ""South Pacific Pictures"", ""id"": 654}]","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}]","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[{""cast_id"": 9, ""character"": ""Paikea Apirana"",...","[{""credit_id"": ""52fe42e7c3a36847f802b7ef"", ""de..."
4400,55180,The Last Big Thing,From a bland tract house on the outskirts of L...,"[Comedy, Drama]","[magazine, independent film, counter-culture, ...","[{""name"": ""Byronic Pose Productions"", ""id"": 17...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 1, ""character"": ""Simon Geist"", ""c...","[{""credit_id"": ""58efcb5a92514125cb000cef"", ""de..."
1392,12437,Underworld: Rise of the Lycans,"A prequel to the first two Underworld films, t...","[Fantasy, Action, Adventure, Science Fiction, ...","[prison, underworld, slavery, castle, vampire,...","[{""name"": ""Lakeshore Entertainment"", ""id"": 126...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 2, ""character"": ""Viktor"", ""credit...","[{""credit_id"": ""5380b9960e0a2624b40081c7"", ""de..."
2574,4995,Boogie Nights,"Set in 1977, back when sex was safe, pleasure ...",[Drama],"[pornography, sex, porn actor, pornographic vi...","[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 8, ""character"": ""Eddie Adams alia...","[{""credit_id"": ""52fe43edc3a36847f8078b3f"", ""de..."
268,10137,Stuart Little,The adventures of a heroic and debonair stalwa...,"[Animation, Fantasy, Family, Comedy]","[brother brother relationship, based on novel,...","[{""name"": ""Columbia Pictures Corporation"", ""id...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 10, ""character"": ""Stuart Little (...","[{""credit_id"": ""52fe43319251416c75007165"", ""de..."
2723,10876,Quills,"A nobleman with a literary flair, the Marquis ...",[Drama],"[asylum, french revolution, french, smuggling,...","[{""name"": ""Fox Searchlight Pictures"", ""id"": 43...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""cast_id"": 1, ""character"": ""The Marquis de S...","[{""credit_id"": ""52fe43c89251416c7501df79"", ""de..."
1660,8054,The Imaginarium of Doctor Parnassus,A traveling theater company gives its audience...,"[Adventure, Fantasy, Mystery]","[circus, immortality, elderly, aftercreditssti...","[{""name"": ""Infinity Features Entertainment"", ""...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[{""cast_id"": 4, ""character"": ""Doctor Parnassus...","[{""credit_id"": ""52fe448ec3a36847f809cd2b"", ""de..."

In [283]:
def convert1(obj):
    L=[]
    obj=ast.literal_eval(obj)
    for i in range(0,3):
        if i<len(obj):
            L.append(obj[i]['name'])
    return L

In [284]:
movies['cast']=movies['cast'].apply(convert1)

In [285]:
movies.sample(10)

,movie_id,title,overview,genres,keywords,production_companies,production_countries,spoken_languages,cast,crew
1387,325133,Neighbors 2: Sorority Rising,A sorority moves in next door to the home of M...,[Comedy],"[alcohol, college, party, sequel, sorority, ne...","[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[Seth Rogen, Rose Byrne, Zac Efron]","[{""credit_id"": ""57337f1092514140bd000a3b"", ""de..."
2891,327,Brother,A Japanese Yakuza gangster’s deadly existence ...,"[Crime, Drama, Thriller]","[brother brother relationship, assassination, ...","[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[Takeshi Kitano, Omar Epps, Claude Maki]","[{""credit_id"": ""52fe4238c3a36847f800d1ef"", ""de..."
2465,318850,The Young Messiah,Tells the story of Jesus Christ at age seven a...,[Drama],"[egypt, jesus christ, gospel, christian, journ...","[{""name"": ""Focus Features"", ""id"": 10146}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[Adam Greaves-Neal, Sara Lazzaro, Vincent Walsh]","[{""credit_id"": ""58cd46d0c3a36850e900c1bd"", ""de..."
2428,15639,Larry the Cable Guy: Health Inspector,A slovenly cable repairman becomes a big-city ...,[Comedy],"[health inspector, food intoxication]","[{""name"": ""Parallel Pictures"", ""id"": 18575}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[Larry the Cable Guy, Iris Bahr, Tony Hale]","[{""credit_id"": ""52fe466d9251416c75077fc9"", ""de..."
2793,59457,Womb,A woman's consuming love forces her to bear th...,"[Romance, Science Fiction]",[],"[{""name"": ""Razor Film Produktion GmbH"", ""id"": ...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[Eva Green, Matt Smith, Lesley Manville]","[{""credit_id"": ""591009b8c3a36864d402c9c1"", ""de..."
4153,198062,Coffee Town,Three thirty-something friends band together w...,[Comedy],"[coffee shop, slacker, thirty something, caref...",[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[Glenn Howerton, Steve Little, Ben Schwartz]","[{""credit_id"": ""52fe4d6c9251416c9111595b"", ""de..."
4177,702,A Streetcar Named Desire,Disturbed Blanche DuBois moves in with her sis...,[Drama],"[southern usa, rape, sister sister relationshi...","[{""name"": ""Charles K. Feldman Group"", ""id"": 13...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[Vivien Leigh, Marlon Brando, Kim Hunter]","[{""credit_id"": ""52fe426dc3a36847f801dac1"", ""de..."
3923,132344,Before Midnight,We meet Jesse and Celine nine years on in Gree...,"[Romance, Drama]","[hotel, airport, hotel room, greece, dream, gr...","[{""name"": ""Castle Rock Entertainment"", ""id"": 9...","[{""iso_3166_1"": ""GR"", ""name"": ""Greece""}, {""iso...","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[Ethan Hawke, Julie Delpy, Seamus Davey-Fitzpa...","[{""credit_id"": ""52fe4b91c3a368484e18f61f"", ""de..."
4353,76487,The Devil Inside,"In Italy, a woman becomes involved in a series...","[Thriller, Horror]","[rome, exorcism, death, demonic possession, fo...","[{""name"": ""Room 101"", ""id"": 6302}, {""name"": ""P...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[Fernanda Andrade, Simon Quarterman, Evan Helm...","[{""credit_id"": ""52fe493dc3a368484e12150f"", ""de..."
3153,11827,Heavy Metal,A glowing orb terrorizes a young girl with a c...,"[Animation, Science Fiction]","[flying car, taxi, heavy metal, cult favorite,...","[{""name"": ""Canadian Film Development Corporati...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}]","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[Rodger Bumpass, Jackie Burroughs, Joe Flaherty]","[{""credit_id"": ""52fe448d9251416c75038ccd"", ""de..."

In [286]:
movie['production_companies']=movie['production_companies'].apply(convert)
movie['production_countries']=movie['production_countries'].apply(convert)
movie['spoken_languages']=movie['spoken_languages'].apply(convert)

In [287]:
movies.sample(15)

,movie_id,title,overview,genres,keywords,production_companies,production_countries,spoken_languages,cast,crew
2354,20483,Catch That Kid,Athletic 12-year-old Maddy (Kristen Stewart) s...,"[Family, Action, Adventure]",[bank robbery],"[Fox 2000 Pictures, Mad Chance, Nimbus Film Pr...",[United States of America],[English],"[Kristen Stewart, Corbin Bleu, Max Thieriot]","[{""credit_id"": ""52fe43e9c3a368484e005541"", ""de..."
1676,265208,Wild Card,When a Las Vegas bodyguard with lethal skills ...,"[Thriller, Crime, Drama]","[gambling, bodyguard, remake]","[Current Entertainment, Lionsgate, Sierra / Af...",[United States of America],[English],"[Jason Statham, Michael Angarano, Milo Ventimi...","[{""credit_id"": ""567846fcc3a3684750000223"", ""de..."
1349,222936,Aloha,A celebrated military contractor returns to th...,"[Drama, Comedy, Romance]","[love triangle, hawaii, satellite, military, d...","[Scott Rudin Productions, Vinyl Films]",[United States of America],"[Pусский, English]","[Bradley Cooper, Emma Stone, Rachel McAdams]","[{""credit_id"": ""55c56d18c3a3682f1c000b2a"", ""de..."
2994,1648,Bill & Ted's Excellent Adventure,"In the small town of San Dimas, a few miles aw...","[Adventure, Comedy, Science Fiction]","[jealousy, journey in the past, sigmund freud,...",[Orion Pictures],[United States of America],"[English, Français, Deutsch, ελληνικά]","[Keanu Reeves, Alex Winter, George Carlin]","[{""credit_id"": ""52fe4308c3a36847f8035623"", ""de..."
2478,10994,White Oleander,A teenager journeys through a series of foster...,[Drama],"[poison, prison, loss of family, loss of fathe...","[Pandora Filmproduktion, John Wells Production...","[Germany, United States of America]",[English],"[Alison Lohman, Michelle Pfeiffer, Cole Hauser]","[{""credit_id"": ""52fe43de9251416c750214bb"", ""de..."
1135,9607,Super Mario Bros.,"Mario and Luigi, plumbers from Brooklyn, find ...","[Adventure, Comedy, Family, Fantasy]","[saving the world, brother brother relationshi...","[Hollywood Pictures, Cinergi Pictures Entertai...","[United Kingdom, United States of America]",[English],"[Bob Hoskins, John Leguizamo, Dennis Hopper]","[{""credit_id"": ""52fe4510c3a36847f80ba51d"", ""de..."
531,203801,The Man from U.N.C.L.E.,"At the height of the Cold War, a mysterious cr...","[Comedy, Action, Adventure]","[spy, cold war, remake, based on tv series, bu...","[Davis Entertainment, Warner Bros., Wigram Pro...",[United States of America],"[Italiano, English, Pусский, Deutsch]","[Henry Cavill, Armie Hammer, Alicia Vikander]","[{""credit_id"": ""5630caf09251416167001e3d"", ""de..."
587,2756,The Abyss,A civilian oil rig crew is recruited to conduc...,"[Adventure, Action, Thriller, Science Fiction]","[ocean, sea, diving suit, flying saucer, nucle...","[Twentieth Century Fox Film Corporation, Light...",[United States of America],[English],"[Ed Harris, Mary Elizabeth Mastrantonio, Micha...","[{""credit_id"": ""52fe436ac3a36847f80528dd"", ""de..."
2517,146,"Crouching Tiger, Hidden Dragon",Two warriors in pursuit of a stolen sword and ...,"[Adventure, Drama, Action, Romance]","[flying, martial arts, taskmaster, comb, tiger...","[Sony Pictures Classics, China Film Co-Product...","[China, Hong Kong, Taiwan, United States of Am...",[普通话],"[Chow Yun-fat, Michelle Yeoh, Zhang Ziyi]","[{""credit_id"": ""52fe421ec3a36847f80055ed"", ""de..."
4489,206197,The Sisterhood of Night,When a teenage girl says she's the victim of a...,"[Mystery, Drama, Thriller]","[witch, woman director]",[],[],[English],"[Kara Hayward, Georgie Henley, Olivia DeJonge]","[{""credit_id"": ""52fe4d17c3a368484e1d6a27"", ""de..."
343,863,Toy Story 2,"Andy heads off to Cowboy Camp, leaving his toy...","[Animation, Comedy, Family]","[museum, prosecution, identity crisis, airplan...",[Pixar Animation Studios],[United States of America],[English],"[Tom Hanks, Tim Allen, Joan Cusack]","[{""credit_id"": ""52fe4284c3a36847f8025073"", ""de..."
154,81188,Rise of the Guardians,When an evil spirit known as Pitch lays down t...,"[Fantasy, Animation, Family]","[dream, santa claus, nightmare, easter bunny, ...",[DreamWorks Animation],[United States of America],"[Français, English]","[Chris Pine, Alec Baldwin, Jude Law]","[{""credit_id"": ""52fe47fe9251416c9107c92f"", ""de..."
678,300168,Dragon Blade,"Huo An, the commander of the Protection Squad ...","[Action, Drama, Adventure]",[],"[Shanghai Film Group, Jackie & JJ Production, ...","[Hong Kong, China]","[English, 普通话]","[Jackie Chan, John Cusack, Adrien Brody]","[{""credit_id"": ""54536744c3a368148d00103d"", ""de..."
1726,4348,Pride & Prejudice,Pride & Prejudice is a humorous story of love ...,"[Drama, Romance]","[bachelor, beautiful, prejudice, suitor, perio...","[Universal Pictures, StudioCanal, Scion Films,...","[France, United Kingdom, United States of Amer...",[English],"[Keira Knightley, Matthew Macfadyen, Rosamund ...","[{""credit_id"": ""52fe43bbc3a36847f806b66b"", ""de..."
4303,11219,The Trouble with Harry,"Trouble erupts in a small, quiet New England t...","[Comedy, Mystery, Thriller]","[small town, chase, wife, leave, murder, suspe...","[Paramount Pictures, Alfred J. Hitchcock Produ...",[United States of America],[English],"[Edmund Gwenn, John Forsythe, Shirley MacLaine]","[{""credit_id"": ""52fe44139251416c750280ab"", ""de..."

In [288]:
def convert2(obj):
    L=[]
    obj=ast.literal_eval(obj)
    for i in obj:
        if ((i['job']=='Director')|(i['job']=='Producer')):
            L.append(i['name'])
    return L

In [289]:
movies['crew']=movies['crew'].apply(convert2)

In [290]:
movies.sample(10)

,movie_id,title,overview,genres,keywords,production_companies,production_countries,spoken_languages,cast,crew
3522,89861,Stiff Upper Lips,Stiff Upper Lips is a broad parody of British ...,[Comedy],"[italy, victorian england, young woman]",[],"[United Kingdom, India]",[English],"[Georgina Cates, Peter Ustinov, Prunella Scales]","[Jeremy Bolt, Gary Sinyor, Gary Sinyor]"
1961,168,Star Trek IV: The Voyage Home,Fugitives of the Federation for their daring r...,"[Science Fiction, Adventure]","[saving the world, san francisco, uss enterpri...",[Paramount Pictures],[United States of America],"[English, suomi]","[William Shatner, Leonard Nimoy, DeForest Kelley]","[Leonard Nimoy, Harve Bennett]"
1381,8843,The Cell,A psychotherapist journeys inside a comatose s...,"[Horror, Science Fiction, Thriller]","[drowning, therapist, virtual reality, serial ...","[New Line Cinema, Avery Pix, Radical Media, Ka...","[Germany, United States of America]",[English],"[Jennifer Lopez, Vincent D'Onofrio, Vince Vaughn]","[Eric McLeod, Julio Caro, Tarsem Singh]"
2790,13435,Antwone Fisher,A sailor prone to violent outbursts is sent to...,"[Drama, Romance]","[u.s. navy, biography]","[Fox Searchlight Pictures, Mundy Lane Entertai...",[United States of America],"[English, 日本語, Pусский, Español]","[Derek Luke, Malcolm David Kelley, Cory Hodges]",[Denzel Washington]
922,13811,Knowing,A teacher opens a time capsule that has been d...,"[Action, Adventure, Drama, Mystery, Science Fi...","[cataclysm, code, suspense, end of the world, ...","[Summit Entertainment, Mystery Clock Cinema, E...","[United Kingdom, United States of America, Aus...",[English],"[Nicolas Cage, Rose Byrne, Chandler Canterbury]","[Steve Tisch, Alex Proyas, Alex Proyas, Todd B..."
3134,217708,Of Horses and Men,A country romance about the human streak in th...,"[Drama, Romance, Comedy]","[horse, snow storm, icelandic]","[Filmhuset Gruppen, Leiknar Myndir]","[Norway, Iceland]","[English, Íslenska, Pусский, Español, svenska]","[Ingvar Eggert Sigurðsson, Charlotte Bøving, S...","[Friðrik Þór Friðriksson, Benedikt Erlingsson]"
2657,9288,Dungeons & Dragons: Wrath of the Dragon God,"Due to a curse from his former master Profion,...","[Action, Adventure, Fantasy]","[fighter, royalty, curse, dragon]","[Skyline Films, Sweetpea Entertainment, Studio...","[Germany, United Kingdom, United States of Ame...",[English],"[Bruce Payne, Mark Dymond, Clemency Burton-Hill]","[Gerry Lively, Wolfgang Esenwein, Steve Clark-..."
4629,13282,Death Race 2000,"In a boorish future, the government sponsors a...","[Action, Comedy, Science Fiction]","[dystopia, street race, reality spoof]",[New World Pictures],[United States of America],[English],"[David Carradine, Simone Griffeth, Sylvester S...","[Paul Bartel, Jim Weatherill]"
3798,133575,The Velocity of Gary,Gary is in love with Valentino. So is Mary Car...,"[Drama, Romance]",[],"[Ventanarosa Productions, Cineville, Columbia ...",[United States of America],[English],"[Vincent D'Onofrio, Salma Hayek, Thomas Jane]",[Dan Ireland]
3429,8998,Friends with Money,"After she quits her lucrative job, Olivia find...","[Comedy, Drama, Romance]","[midlife crisis, marriage, money, divorce, fas...",[Sony Pictures],[United States of America],[English],"[Catherine Keener, Jason Isaacs, Timm Sharp]","[Anthony Bregman, Nicole Holofcener]"

In [291]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [292]:
movies.sample(15)

,movie_id,title,overview,genres,keywords,production_companies,production_countries,spoken_languages,cast,crew
4693,14758,Good Dick,"[A, fidgety,, wisecracking, video, store, cler...","[Comedy, Drama, Romance]","[sexuality, roommate, misfit, independent film...","[Good Dick, Morning Knight, Present Pictures]",[United States of America],[English],"[Marianna Palka, Jason Ritter, Eric Edelstein]","[Jason Ritter, Marianna Palka, Marianna Palka,..."
716,11128,Ladder 49,"[Under, the, watchful, eye, of, his, mentor,, ...","[Drama, Action, Thriller]","[ledge, practical joke]","[Casey Silver Productions, Beacon Communicatio...",[United States of America],[English],"[Joaquin Phoenix, John Travolta, Jacinda Barrett]","[Casey Silver, Jay Russell]"
464,159824,Hotel Transylvania 2,"[When, the, old-old-old-fashioned, vampire, Vl...","[Animation, Comedy, Family]","[transylvania, hotel, witch, technology, magic...","[Columbia Pictures, Sony Pictures Animation]",[United States of America],"[English, ภาษาไทย]","[Adam Sandler, Andy Samberg, Selena Gomez]","[Robert Smigel, Genndy Tartakovsky]"
1902,18975,The Adventures of Pinocchio,"[One, of, puppet-maker, Geppetto's, creations,...","[Animation, Family, Fantasy]","[italy, father son relationship, pinocchio, lo...","[New Line Cinema, The Kushner-Locke Company, S...","[Czech Republic, France, Germany, United Kingd...","[English, Italiano]","[Martin Landau, Jonathan Taylor Thomas, Genevi...",[Steve Barron]
1606,4513,30 Days of Night,"[This, is, the, story, of, an, isolated, Alask...","[Horror, Thriller]","[sunrise, winter, vampire, marriage crisis, al...","[Columbia Pictures, Dark Horse Entertainment, ...","[New Zealand, United States of America]",[English],"[Josh Hartnett, Melissa George, Ben Foster]","[Sam Raimi, Robert Tapert, Joseph Drake, David..."
2923,249164,If I Stay,"[Based, on, Gayle, Forman's, novel, of, the, s...",[Drama],"[coma, musician, teenage girl, car accident, t...","[New Line Cinema, Metro-Goldwyn-Mayer (MGM)]",[United States of America],[English],"[Chloë Grace Moretz, Jamie Blackley, Liana Lib...","[Alison Greenspan, R.J. Cutler]"
3045,328425,The Gift,"[A, husband, and, wife, try, to, reinvigorate,...","[Thriller, Mystery]","[detective, stalker, gift, bully, psychologica...","[Blumhouse Productions, Blue-Tongue Films, Hua...",[United States of America],[English],"[Jason Bateman, Rebecca Hall, Joel Edgerton]","[Joel Edgerton, Joel Edgerton, Jason Blum, Reb..."
3458,10160,A Nightmare on Elm Street 5: The Dream Child,"[Alice,, having, survived, the, previous, inst...","[Horror, Thriller]","[nun, baby, monster, asylum, nightmare, supern...",[New Line Cinema],[United States of America],[English],"[Robert Englund, Lisa Wilcox, Erika Anderson]","[Stephen Hopkins, Robert Shaye, Rupert Harvey]"
821,156022,The Equalizer,"[In, The, Equalizer,, Denzel, Washington, play...","[Thriller, Action, Crime]","[corruption, assassin, hostage, fbi, hitman, r...","[Columbia Pictures, Village Roadshow Pictures,...",[United States of America],[English],"[Denzel Washington, Marton Csokas, Chloë Grace...","[Steve Tisch, Mace Neufeld, Denzel Washington,..."
1823,11024,Scooby-Doo 2: Monsters Unleashed,"[When, Mystery,, Inc., are, guests, of, honor,...","[Mystery, Fantasy, Adventure, Comedy]","[detective, monster, engine, based on tv serie...","[Mosaic Media Group, Warner Bros.]",[United States of America],[English],"[Freddie Prinze Jr., Sarah Michelle Gellar, Ma...","[Charles Roven, Raja Gosnell, Richard Suckle]"
2293,62630,The Devil's Double,"[A, chilling, vision, of, the, House, of, Sadd...","[Drama, Action, Thriller, Crime, War]","[palace, impostor, pervertion]","[Corrino Media Corporation, Corsan, Staccato F...","[Netherlands, Belgium]",[English],"[Dominic Cooper, Ludivine Sagnier, Raad Rawi]","[Lee Tamahori, Paul Breuls, Catherine Vandelee..."
1420,8197,Midnight in the Garden of Good and Evil,"[A, visiting, city, reporter's, assignment, su...","[Crime, Drama, Mystery, Thriller]","[drag queen, voodoo, savannah]","[Warner Bros., Malpaso Company]",[United States of America],[English],"[John Cusack, Kevin Spacey, Jude Law]","[Clint Eastwood, Clint Eastwood, Arnold Stiefel]"
4626,47534,Fighting Tommy Riley,"[An, aging, trainer, and, a, young, fighter,, ...","[Action, Adventure, Drama]","[boxer, massage, unrequited love, locker room,...",[],[],[English],"[J.P. Davis, Eddie Jones, Christina Chambers]",[Eddie O'Flaherty]
4266,39209,Shalako,"[Sean, Connery, is, Shalako,, a, guide, in, th...",[Western],"[native american, gunfighter, hunting party]","[Central Cinema Company Film, Palomar Pictures...","[United States of America, Germany]","[Deutsch, English, Español]","[Sean Connery, Brigitte Bardot, Jack Hawkins]","[Artur Brauner, Euan Lloyd, Edward Dmytryk, Ha..."
1179,7461,Vantage Point,"[The, attempted, assassination, of, the, Ameri...","[Drama, Action, Thriller, Crime]","[bomb, terror, spain, usa president, terrorist...","[Columbia Pictures, Original Film, Kanzaman, R...",[United States of America],"[Español, English]","[Dennis Quaid, Matthew Fox, Forest Whitaker]","[Neal H. Moritz, Pete Travis]"

In [293]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [294]:
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies['production_companies']=movies['production_companies'].apply(lambda x:[i.replace(" ","") for i in x])
movies['production_countries']=movies['production_countries'].apply(lambda x:[i.replace(" ","") for i in x])
movies['spoken_languages']=movies['spoken_languages'].apply(lambda x:[i.replace(" ","") for i in x])

In [295]:
movies.sample(15)

,movie_id,title,overview,genres,keywords,production_companies,production_countries,spoken_languages,cast,crew
4748,9372,Super Size Me,"[Morgan, Spurlock, subjects, himself, to, a, d...","[Documentary, Comedy, Drama]","[experiment, health, junkfood, foodindustry, f...",[KathburPictures],[UnitedStatesofAmerica],[English],"[MorganSpurlock, DarylIsaacs, LisaGanjhu]","[MorganSpurlock, MorganSpurlock]"
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[rustybearentertainment, luckycrowfilms]",[UnitedStatesofAmerica],[English],"[DrewBarrymore, BrianHerzlinger, CoreyFeldman]","[BrianHerzlinger, JonGunn, BrettWinn]"
243,1593,Night at the Museum,"[Chaos, reigns, at, the, natural, history, mus...","[Action, Adventure, Comedy, Family, Fantasy]","[museum, skeleton, nightshift, chaos, genghisk...","[IngeniousFilmPartners, TwentiethCenturyFoxFil...","[UnitedStatesofAmerica, UnitedKingdom]","[English, Italiano, עִבְרִית]","[BenStiller, JakeCherry, CarlaGugino]","[ChrisColumbus, ShawnLevy, ShawnLevy, MichaelB..."
2984,10314,She's All That,"[High, school, hotshot, Zach, Siler, is, the, ...","[Comedy, Romance]","[tvstar, jeep, volleyball, misfit, teenangst, ...","[MiramaxFilms, TapestryFilms, FilmColony]",[UnitedStatesofAmerica],[English],"[FreddiePrinzeJr., RachaelLeighCook, MatthewLi...","[RichardN.Gladstein, PeterAbrams, RobertL.Levy..."
4397,66195,The Perfect Host,"[A, criminal, on, the, run, cons, his, way, in...","[Comedy, Thriller, Crime]","[swimmingpool, teakettle, congaline, spitinthe...",[SplendidFilm],[UnitedStatesofAmerica],[English],"[DavidHydePierce, ClayneCrawford, NathanielPar...",[NickTomnay]
2690,12403,A Perfect Getaway,"[For, their, honeymoon,, newlyweds, Cliff, and...","[Thriller, Mystery, Adventure]","[hawaii, honeymoon, doublemurder, murder]","[DavisEntertainment, RelativityMedia, Rogue, Q...",[UnitedStatesofAmerica],[English],"[MillaJovovich, TimothyOlyphant, SteveZahn]","[DavidTwohy, MarkCanton, RyanKavanaugh, Tucker..."
2439,58048,Shanghai Surprise,"[Glendon, Wasey, is, a, fortune, hunter, looki...",[Adventure],[],"[HandMadeFilms, VistaOrganisation,The]",[UnitedKingdom],[English],"[Madonna, SeanPenn, PaulFreeman]",[JimGoddard]
2213,10773,Mrs Henderson Presents,"[Eccentric, 70-year-old, widow, purchases, the...","[Comedy, Drama]","[worldwarii, widow, musical, theatremilieu, na...",[],[UnitedKingdom],[English],"[JudiDench, BobHoskins, WillYoung]","[BobHoskins, StephenFrears, NormaHeyman, David..."
438,6964,Something's Gotta Give,"[Harry, Sanborn, is, an, aged, music, industry...","[Drama, Comedy, Romance]","[agedifference, ladykiller, womandirector]","[ColumbiaPicturesCorporation, WaverlyFilms, Wa...",[UnitedStatesofAmerica],"[Français, English]","[JackNicholson, DianeKeaton, KeanuReeves]","[NancyMeyers, NancyMeyers, BruceA.Block]"
560,10477,Driven,"[Talented, rookie, race-car, driver, Jimmy, Bl...",[Action],"[competition, running, career, idol, racingcar]","[EpsilonMotionPictures, FranchisePictures, Tra...","[Australia, Canada, UnitedStatesofAmerica]","[English, Deutsch, Español]","[KipPardue, RobertSeanLeonard, TilSchweiger]","[SylvesterStallone, RennyHarlin, RennyHarlin]"
2951,11109,Vera Drake,"[Abortionist, Vera, Drake, finds, her, beliefs...","[Crime, Drama]","[england, motherrole, women'sprison, police, n...","[IngeniousFilmPartners, LesFilmsAlainSarde, UK...","[UnitedKingdom, France]",[English],"[ImeldaStaunton, SallyHawkins, RichardGraham]","[AlainSarde, SimonChanningWilliams, MikeLeigh]"
4420,34592,ZMD: Zombies of Mass Destruction,"[An, idyllic, island, town, is, under, attack,...",[Horror],"[racist, religion]",[SplendidFilm],[UnitedStatesofAmerica],[English],"[JanetteArmand, DougFahl, CooperHopkins]",[KevinHamedani]
8,767,Harry Potter and the Half-Blood Prince,"[As, Harry, begins, his, sixth, year, at, Hogw...","[Adventure, Fantasy, Family]","[witch, magic, broom, schoolofwitchcraft, wiza...","[WarnerBros., HeydayFilms]","[UnitedKingdom, UnitedStatesofAmerica]",[English],"[DanielRadcliffe, RupertGrint, EmmaWatson]","[DavidHeyman, DavidYates, DavidBarron, TimLewis]"
528,612,Munich,"[During, the, 1972, Olympic, Games, in, Munich...","[Drama, Action, History, Thriller]","[paris, assassination, israel, hotelroom, 1970...","[DreamWorksSKG, UniversalPictures, AmblinEnter...","[Canada, UnitedStatesofAmerica, France]","[العربية, Deutsch, ελληνικά, English, Français...","[EricBana, DanielCraig, CiaránHinds]","[StevenSpielberg, StevenSpielberg, KathleenKen..."
1111,834,Underworld: Evolution,"[As, the, war, between, the, vampires, and, th...","[Fantasy, Action, ScienceFiction, Thriller]","[budapest, key, vampire, light, werewolf, evol...","[LakeshoreEntertainment, ScreenGems]",[UnitedStatesofAmerica],"[English, Français, Magyar]","[KateBeckinsale, ScottSpeedman, TonyCurran]","[TomRosenberg, LenWiseman, KevinGrevioux, Gary..."

In [296]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['production_companies']+movies['production_countries']+movies['spoken_languages']+movies['cast']+movies['crew']

In [297]:
movies=movies[['movie_id','title','tags']]

In [298]:
movies.sample(10)

,movie_id,title,tags
4282,42033,Def-Con 4,"[Two, men, and, a, woman, circle, the, globe, ..."
1333,96721,Rush,"[A, biographical, drama, centered, on, the, ri..."
3653,51384,"Lovely, Still","[A, holiday, fable, that, tells, the, story, o..."
1912,10074,Hot Rod,"[For, Rod, Kimball,, performing, stunts, is, a..."
2963,80271,LOL,"[In, a, world, connected, by, YouTube,, iTunes..."
1735,23172,The Spy Next Door,"[Former, CIA, spy, Bob, Ho, takes, on, his, to..."
4716,335244,Antarctic Edge: 70° South,"[In, 2014,, scientists, declared, West, Antarc..."
4783,185465,Manito,"[Fifteen, years, ago,, their, Washington, Heig..."
3319,11022,Narc,"[An, undercover, narc, dies,, the, investigati..."
318,9408,Surf's Up,"[Cody, is, a, surfing, penguin, from, Shiverpo..."

In [299]:
movies['tags']=movies['tags'].apply(lambda x:" ".join(x))

/var/folders/_9/85pjm9dd3rq4wsfsg98prgj00000gn/T/ipykernel_6137/2833023431.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['tags'].apply(lambda x:" ".join(x))

In [300]:
movies.sample(10)

,movie_id,title,tags
4715,13187,A Charlie Brown Christmas,When Charlie Brown complains about the overwhe...
223,2789,The Chronicles of Riddick,After years of outrunning ruthless bounty hunt...
3265,209263,Enough Said,Eva is a divorced soon-to-be empty-nester wond...
4360,361475,Departure,An English mother and her teenage son spend a ...
3950,22488,Love's Abiding Joy,The continued Westward journey of settlers Mis...
3458,10160,A Nightmare on Elm Street 5: The Dream Child,"Alice, having survived the previous installmen..."
2723,10876,Quills,"A nobleman with a literary flair, the Marquis ..."
3032,11891,Kung Pow: Enter the Fist,"A movie within a movie, created to spoof the m..."
2010,6973,In the Valley of Elah,A career officer and his wife work with a poli...
3600,747,Shaun of the Dead,"Shaun lives a supremely uneventful life, which..."

In [301]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [302]:
movies['tags']=movies['tags'].apply(stem)

/var/folders/_9/85pjm9dd3rq4wsfsg98prgj00000gn/T/ipykernel_6137/4136005365.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['tags'].apply(stem)

In [303]:
movies.sample()

,movie_id,title,tags
2293,62630,The Devil's Double,a chill vision of the hous of saddam hussein c...

In [304]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
vectors=cv.fit_transform(movies['tags']).toarray()

In [307]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [308]:
similarity

array([[1.        , 0.1165631 , 0.17391304, ..., 0.08178608, 0.04301324,
        0.04445542],
       [0.1165631 , 1.        , 0.09325048, ..., 0.06577935, 0.04612656,
        0.07150969],
       [0.17391304, 0.09325048, 1.        , ..., 0.06133956, 0.04301324,
        0.04445542],
       ...,
       [0.08178608, 0.06577935, 0.06133956, ..., 1.        , 0.08091134,
        0.0836242 ],
       [0.04301324, 0.04612656, 0.04301324, ..., 0.08091134, 1.        ,
        0.13193985],
       [0.04445542, 0.07150969, 0.04445542, ..., 0.0836242 , 0.13193985,
        1.        ]], shape=(4806, 4806))

In [311]:
def recommend(movie):
    movie_index=movies[movies['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(movies.iloc[i[0]].title)

In [313]:
recommend('Batman Begins')

The Dark Knight
Batman
The Dark Knight Rises
Batman
Batman v Superman: Dawn of Justice

In [314]:
import pickle

In [316]:
pickle.dump(movies.to_dict(),open('movies.pkl','wb'))

In [317]:
pickle.dump(similarity,open('similarity.pkl','wb'))